### ISSUE TITLE
Visualization of model outputted predictions

### ISSUE THREAD

**Issue by dufaultc** [McMasterAI/Radiology-and-AI#36]

**Comment by matthewcso** [comment]
1. Visualize 2D image of the tumor and the segmentation map and how they overlap (easier)
2. Visualize 3D image of the tumor and the segmentation map and how they overlap (harder)
potential ideas:
- can use 3D slicer (separate software) to generate good 2D images, or can just do this with slicing in matplotlib/numpy
- Can visualize 3D images by making meshes of tumor/segmentations, or by setting one or both the be translucent, or however you'd like
