### ISSUE TITLE
Find examples in research of deep learning for tumour characterization 

### ISSUE THREAD

**Issue by dufaultc** [McMasterAI/Radiology-and-AI#44]
- Tumour progression vs pseudo-progression
- Cancer Type (Brain cancer vs Metastases)
- Immunotherapy response
- Any other types

Look into types of architecture, where they got the data, etc

**Comment by HamzaIssa14** [comment]
[https://app.zenhub.com/files/312700654/5118698d-d0d2-4d8b-8f7c-01777059d20c/download](https://app.zenhub.com/files/312700654/5118698d-d0d2-4d8b-8f7c-01777059d20c/download)
