### ISSUE TITLE
Research tumour segmentation papers

### ISSUE THREAD

**Issue by dufaultc** [McMasterAI/Radiology-and-AI#49]
Report the:
-Model architecture used
-Data augmentation method
-The performance metrics of the model
-Data used if available

Focused on people try to complete Brats challenge or something similar

**Comment by HamzaIssa14** [comment]
[Data extraction of Unet Architectures.docx](https://github.com/McMasterAI/Radiology-and-AI/files/5811411/Data.extraction.of.Unet.Architectures.docx)

**Comment by HamzaIssa14** [comment]
[Data.extraction.of.Unet.Architectures.pdf](https://github.com/McMasterAI/Radiology-and-AI/files/5811501/Data.extraction.of.Unet.Architectures.pdf)

**Comment by HamzaIssa14** [comment]
Data Augmentation approach paper:
https://arxiv.org/abs/2010.13372
