### ISSUE TITLE
Report for us the methodology used in the paper sent by Fatema

### ISSUE THREAD

**Issue by dufaultc** [McMasterAI/Radiology-and-AI#52]

**Comment by HamzaIssa14** [comment]
[MACHINE LEARNING NONSEGMENTED GLIOMAS DATA EXTRACTION.pdf](https://github.com/McMasterAI/Radiology-and-AI/files/5852590/MACHINE.LEARNING.NONSEGMENTED.GLIOMAS.DATA.EXTRACTION.pdf)
