### ISSUE TITLE
Speed up elastic transform augmentation / power transfrom optimization

### ISSUE THREAD

**Issue by dufaultc** [McMasterAI/Radiology-and-AI#61]
- Write  up of how augmentations work
- Try to find existing implementation to use instead of the current one
- Cameron will use to speed up the implementations

-Elastic deformations/augmentation

**Comment by HamzaIssa14** [comment]
[Elastic Deformation.pdf](https://github.com/McMasterAI/Radiology-and-AI/files/5889433/Elastic.Deformation.pdf)
