### ISSUE TITLE
Look into Normalization method sent by Fateme

### ISSUE THREAD

**Issue by dufaultc** [McMasterAI/Radiology-and-AI#65]

**Comment by matthewcso** [comment]
Important takeaways from “Radiomics Repeatability Pitfalls in a Scan-Rescan MRI Study of Glioblastoma”

Segmentation, Annotation and Preprocessing

0.	Patients were scanned twice before treatment, at two times between 2-6 days apart. 
1.	Segmentations of enhancing lesions on T1-weighted postcontrast sequences and areas of T2 abnormality on T2-weighted FLAIR sequences were performed by expert raters...
2.	After segmentation, each patient’s T1-weighted postcontrast sequences were registered...
3.	The N4 bias-correction algorithm was applied to all images using the Nipype...
4.	Whole-brain extraction was performed on T1-weighted postcontrast images using the ROBEX...
5.	Normalization was performed either as part of feature extraction, or separately by using a histogram-matching technique.
6.	Derived union masks by registering rescan to scan and taking the union of both masks separately...
7.	Used PyRadiomics to extract radiomic features

Note: The authors say somewhere in this section that "Histogram matching of the non-ROI region is a common normalization technique in radiomics". It is unclear whether or not they use histogram matching based on the non-ROI region, or ALL regions.

Main results
1.	Default binning method for histograms is ineffective, relative binning with 256 bins used instead
2.	Z-score normalization/histogram matching results in more similar histogram distributions 
3.	Z-score normalization and histogram matching improves repeatability of intensity features for T2w but not T1w
4.	Z-score normalization does not change repeatability of texture features for T2w, but histogram matching does. Neither improve repeatability for T1w.
5.	Shape features are computed exclusively on manual segmentations, and they are highly consistent between scan and rescan.
6.	Overall, image acquisition has a greater influence on radiomic feature repeatability compared to rater variability in segmentation

My conclusions

Image normalization could be important, but assuming that the segmentation, annotation, and preprocessing section is in order, the authors demonstrate that the manual segmentations are actually consistent across scans even without any sort of normalization.
